name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest tests

      - name: Train model and save artifact
        run: |
          python src/train_model.py
        # Upload the model as an artifact
      - name: Upload model
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: src/path_to_your_model_file
