name: CI/CD for Diabetes Model

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:

  test:
  
    runs-on: ubuntu-latest  # Use a Linux runner, or choose another runner if needed
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Set the Python version you're using

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install tensorflow keras scikit-learn numpy pandas matplotlib seaborn imbalanced-learn

      - name: Preprocess data
        run: | 
          cd ${{ github.workspace }}         
          python "Model/Preprocessing.py"

      - name: Train model
        run: |
          cd ${{ github.workspace }}/Model 
          python "NN.py"
          
      - name: Run unit test
        run: | 
          cd ${{ github.workspace }}/Model 
          python -m unittest "Unit-test.py"

      - name: Save Model as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: diabetes-model  # Artifact name
            # Specify the path to where your model is saved

      - name: Download Model Artifact
        uses: actions/download-artifact@v2
        with:
          name: diabetes-model  # Artifact name

  download_artifact:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Model Artifact
        uses: actions/download-artifact@v4
        with:
          name: diabetes-model  # Name of the artifact to download
          path: C:\Users\Sid\Desktop\DSOR 752  # Directory where the artifact will be downloaded

      - name: List downloaded files
        run: ls C:\Users\Sid\Desktop\DSOR 752  # Confirm that the files were downloaded
